name: FrameDupe
version: 1.0
main: me.hexa.framedupe.FrameDupe
api-version: 1.12.2
authors: [ Hexa ]
description: Plugin to dupe items when breaking an item frame based on probability
website: www.etheranarchy.org
commands:
  framedupereload:
    usage: /framedupereload